#!/usr/bin/env python3

import sys
import error
import loader
import lexer
import parser
import backend_gcc

def main():
	if len(sys.argv) < 2:
		error.fatal(0, "no source file given as first argument")
	
	src_name = sys.argv[1]
	src = loader.load_source(src_name)
	tokens = lexer.lex(src)
	tree = parser.parse(tokens)
	
	#print(src_name)
	#print(src)
	print(tokens)
	print(tree)
	
	if error.count > 0:
		error.fatal(0, "found", error.count, "error(s), can not generate target code")
	
	code = backend_gcc.gen_code(tree)
	
	print(code)
	
	backend_gcc.compile_code(src_name, code)

main()
